### ISSUE TITLE
Capturing doesn't work anymore

### ISSUE THREAD

**Issue by Popsch** [sabof/org-bullets#1]
When I enable org-bullets, then I don't see the text in capture mode anymore. I enable org-bullets in the org-mode-hook.

I use this theme:
(require 'color-theme)
(color-theme-jsc-light)

Then after calling (org-capture) , I don't see the text I type next to the TODO item.

**Comment by sabof** [comment]
I'm not very familiar with org-capture, but there might be some unexpected interactions between overlays. You could try closing and reopening the parent title.
If the problem persists, you might want to disable org-bullets in that file, by adding the following in the end:

```
* Local Variables
# Local Variables:
# eval: (org-bullets-mode 0)
# End:
```
