### ISSUE TITLE
symbols shows differently in org file

### ISSUE THREAD

**Issue by xarthurx** [sabof/org-bullets#10]
Hi,

I changed the bullet as the my font does not have the default one.
However, by changing the bullet to:

 (setq org-bullets-bullet-list '("◈" "◆" "◊" "✸"))

The first symbol show a "square" in org file, the rest are fine.

Not sure if it is the org-bullet problem, but the symbol "◈" was displayed fine in .emacs file, and was also displayed fine as normal text in any .org file, but only display incorrectly as the title symbol as the first level sign in an org file.

Any solutions?

**Comment by sabof** [comment]
I don't know what might be causing this, but I'll have a look

**Comment by stardiviner** [comment]
This symbol might not supported by your font.

**Comment by xarthurx** [comment]
Actually, it is because some font setting that set the first line in other fonts...
Anyway, sorry for the confusion.

**Comment by sabof** [comment]
I still appreciate the report -- what happened to you might happen to someone else.
