### ISSUE TITLE
[Feature Request] Bullets for TODOs

### ISSUE THREAD

**Issue by ghost** [sabof/org-bullets#14]
I want to suggest something like this:

Suppose we have ('*' represents unicode bullet from this package):

```
* Heading 1
* Heading 2
```

Now, setting a `TODO` on a heading should result in:

```
☐ Heading 1 # TODO, using a unicode "ballot box"
☑ Heading 2 # DONE, using a unicode "ballot box with check"
```

**Comment by ghost** [comment]
Possible characters can be:
- U+2714 ✔ heavy check mark
- U+2717 ✗ ballot x
- U+2611 ☑ ballot box with check
- U+2610 ☐ ballot box

Users can be provided options to use other symbols, such as smileys etc.

Still, this is all hypothetical, as I don't know if this can (and will be) implemented or not.

**Comment by theophilusx** [comment]
There is an alternative way to achieve something similar. If you define your toto keyword sequences so that they include a leading UTF8 charcter, you can get similar look. i.e. 

```
(sequence " ☐ TODO(t)" " ☑ DONE(d)")
```

The limitation of this is that it isn't backwards compatible i.e. old todo sequences won't work and I don't know what impact this might have on export backends.

**Comment by msanders** [comment]
Here's another workaround that preserves existing text while allowing for unicode checklists in org mode:

```Emacs Lisp

(font-lock-add-keywords 'org-mode
                        '(("\\(?:\\(?:- \\)?\\[ ]\\)"
                           (0 (prog1 () (compose-region
                                         (match-beginning 0)
                                         (match-end 0) "☐"))))))

(font-lock-add-keywords 'org-mode
                        '(("\\(?:\\(?:- \\)?\\[X]\\)"
                           (0 (prog1 () (compose-region
                                         (match-beginning 0)
                                         (match-end 0) "☑"))))))

;; From http://www.howardism.org/Technical/Emacs/orgmode-wordprocessor.html
(font-lock-add-keywords 'org-mode
                        '(("^ +\\([-*]\\) "
                           (0 (prog1 () (compose-region (match-beginning 1)
                                                        (match-end 1)
                                                        "•"))))))
```

It might be worth building this into `org-bullets`, though it seems like it might be unmaintained.

**Comment by ppareit** [comment]
@msanders it seems like the following fork takes pull requests and is also the one that is used on melpa:
https://github.com/emacsorphanage/org-bullets
