### ISSUE TITLE
Leading asterisks have wrong background color in terminal Emacs

### ISSUE THREAD

**Issue by stefanavey** [sabof/org-bullets#16]
I'm not sure if you intended this to be compatible with Emacs run from the terminal but I see the leading stars (even when I set the hidestars startup option for org mode) because they have a black background.

When I open the same file in the GUI Emacs I do not see this black background so the leading stars are hidden and it looks clean.

![org-bullets](https://cloud.githubusercontent.com/assets/6976841/12648408/d2b3d64e-c5a7-11e5-819b-5aa0579c9f20.png)

**Comment by fosskers** [comment]
I use emacs strictly out of the terminal, and yeah this doesn't look so great.

**Comment by Kaligule** [comment]
[This](http://stackoverflow.com/questions/5795451/how-to-detect-that-emacs-is-in-terminal-mode) could help to determine if the buffer lives in a gui or in a textbased terminal.

**Comment by evadnoob** [comment]
I use rxvt-unicode/urxvt and I have the same issue:

◉ This is a test of org-bullets mode
*○ two stars
**✸ three stars

**Comment by stefanavey** [comment]
I was able to solve my problem a while ago.  I think it was solved by redefining the org-hide face.  This now works in my terminal Emacs as well (you'll have to change the color depending on your background color).

             ;; Redefine a face from org-faces.el                                                                                                           
             (defface org-hide
               '((((background light)) (:foreground "color-231"))
                 (((background dark)) (:foreground "black")))
               "Face used to hide leading stars in headlines.                                                                                               
               The foreground color of this face should be 
               equal to the background color of the frame."
               :group 'org-faces)

**Comment by Kaligule** [comment]
@stefanavey  I don't think that this alone solved the problem, since org-bullets doesn't seem to respect the org-hide face at all. It doesn't work for me. Could you provide additional information or even you init file?

**Comment by Kaligule** [comment]
I added a pullrequest so org-bullet does respect org-hide. Lets hope @sabof is still maintaing this repo.

**Comment by Kaligule** [comment]
Btw making text invisible (so that it looks like like blank space) seems to be difficult and has been discussed [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=15815).

**Comment by stefanavey** [comment]
@Kaligule you are right this alone won't fix it.  I thought that was my fix but it's been a long time and I forgot I stopped using org-bullets (for this reason).   Sorry for the confusion - I hope it gets fixed and I'd love to try it out again.

**Comment by sus007** [comment]
@stefanavey @fosskers @sabof @Kaligule Guys, any updates or fixes regarding this issue ? :confused: 
![emacs](https://user-images.githubusercontent.com/7630815/42734800-8a12fbae-8869-11e8-9e74-e0b526947105.png)

**Comment by fosskers** [comment]
@sus007 I switched to spacemacs about a year ago, where `org-bullets` works perfectly out of the box.

I usually use the GUI mode, but I tested it quickly in the terminal and I don't see this bullets problem there either.

**Comment by stefanavey** [comment]
@sus007 I'm back to using `org-bullets` and it works fine for me (even in terminal) when using a light theme.  I can reproduce your screenshot using a dark theme (where the stars are "hidden" with correct face but have grey background).  Haven't tried to fix it since I normally don't use a dark background but I'll look into it if I have time.

**Comment by sus007** [comment]
@stefanavey I do use dark background and I had never tested an actual dark color scheme before with Emacs. I am ok with this for the time being. :smiley: Thanks.
![ema](https://user-images.githubusercontent.com/7630815/42745040-50a20c8e-88f0-11e8-85e6-d3050057023c.png)

**Comment by alphapapa** [comment]
@sus007 I haven't seen icons in place of to-do keywords before.  Do you have a source for how you did that?  :)

**Comment by ordicker** [comment]
I got this bug when switching between themes. 
It was also mentioned [here](https://github.com/syl20bnr/spacemacs/issues/4688) but wasn't resolved.

I don't think it is the same problem, whoever it is looks the same.

**Comment by alphapapa** [comment]
@d1cker 

* https://github.com/syl20bnr/spacemacs/issues/4688#issuecomment-172947851
* https://github.com/syl20bnr/spacemacs/issues/4688#issuecomment-327531629

**Comment by ordicker** [comment]
@alphapapa 
Thanks!
