### ISSUE TITLE
Autoload and customize

### ISSUE THREAD

**Issue by haxney** [sabof/org-bullets#2]
It would be nice to sprinkle some `;;;###autoload` declarations in there so that people could activate `org-bullets` without having to use `require` or `add-hook`. You could have a `defcustom` variable which, when set, will turn on `org-bullets` in all new `org-mode` buffers. If you `autoload` that `defcustom`, users could enable `org-bullets` purely through Customize.

**Comment by sabof** [comment]
I've seen autoloads, but never really knew how they worked. 

I'm still not quite clear about autoloading+defcutsom+enabling through cutomize.  Should I define the org-bullets-mode variable as defcustom? Do defcustoms`*` "inform" of a function/variable existing in a certain file, or can they execute arbitrary code?

```
* that was "autoloads"
```

**Comment by haxney** [comment]
Check out the info page `(elisp) Autoload` for a description. The gist is that you add a special comment above a `defun`, `defvar`, `defcustom`, etc. and when you run one of the `update-*-autoloads` functions, the forms marked with the magic comment are written to a generated elisp file. By loading the "autoloads file", Emacs marks the functions and variables as autoloaded, meaning that whenever something tries to access the variable/function, the linked file is loaded.

For example, if you mark a function as autoloaded, the elisp file containing the function definition won't actually be loaded until you actually try to execute the function. This lets you set up a whole bunch of modes and features without actually loading all of the relevant files. The main benefit is to cut down on startup time. package.el automatically scans through all of the elisp files and generates a "foo-autoloads.el" file (for a hypothetical package named "foo").

`defcustom` sets up a variable to be editable through "M-x customize", which lets the user set up variables without having to enter them manually into his/her `.emacs.d/init.el`. With all of this together, a user will be able to install the package, add some settings to their customization file, and then use the mode without having to write a single line of elisp.

I'll fork and submit a pull request.

**Comment by sabof** [comment]
Thanks, I'll have a look and merge it.
