### ISSUE TITLE
package cl is deprecated, need to port the cl functions from cl-lib for emacs 27

### ISSUE THREAD

**Issue by hemanthgu** [sabof/org-bullets#27]
The package 'cl is deprecated. the common-lisp functions used in org-bullets needs to ported to functions from cl-libs.
use of org-bullets raises warning on emacs startup.

**Comment by Phundrak** [comment]
org-bullets has been unmaintained for seven years now, and it is seriously out of date. You might want to switch to [org-superstar](https://github.com/integral-dw/org-superstar-mode) instead.

**Comment by hemanthgu** [comment]
thank you for the tip.
