### ISSUE TITLE
Display of inline tasks not so nice

### ISSUE THREAD

**Issue by andersjohansson** [sabof/org-bullets#5]
Inline tasks (see org-inlinetask.el) shows the last two bullets (I think) and this doesn't look so nice with org-bullets. You get something like: "*◉" when using org-indent-mode. I don't know what would be the best solution because I guess the display of the last two stars is there to mark this as an inlinetask. Maybe org-bullets could replace both?

**Comment by sabof** [comment]
I've added a fix at the devel branch. See if it works for you.

**Comment by andersjohansson** [comment]
Yes, it seems to work really nicely, displaying two "unicode bullets". Thanks!
