### ISSUE TITLE
Show bullet even in the code snippet

### ISSUE THREAD

**Issue by mikulely** [sabof/org-bullets#6]
emacs version: GNU Emacs 24.3.1 installed on Archlinux
org-bullets version: org-bullets-20131106.1908 installed from elpa.

![unexpected_bullet](https://f.cloud.github.com/assets/4464227/1548263/add74ece-4dc1-11e3-879e-8bc3964c0a3b.png)

![expected_bullet](https://f.cloud.github.com/assets/4464227/1548262/a3c34bc2-4dc1-11e3-868e-6bb45199bfce.png)

**Comment by sabof** [comment]
This case is generally broken in org-mode. Ex. you can fold this line with TAB, or navigate to it with `outline-next-visible-heading`. I don't see much point in fixing this for org-bullets in view of this.

**Comment by sabof** [comment]
You might want to try setting `org-src-preserve-indentation'  to nil, if this is especially problematic. Have a look at the documentation for this variable for an explanation.
